### ISSUE TITLE
Blank page shows up?

### ISSUE THREAD

**Issue by kmader** [kmader/nbpolynote#1]
when you start a binder eg https://hub.gke.mybinder.org/user/kmader-nbpolynote-uwb2ue4j/polynote/ the first page loads but nothing else works
because the urls are relative
```
<html>
 <head>
<title>Polynote</title>
<meta charset="utf-8" />
<base href="/" />
<link rel="stylesheet" type="text/css" href="/style/styles.css" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.css" integrity="sha384-b/NoaeRXkMxyKcrDw2KtVtYKkVg3dA0rTRgLoV7W2df3MzeR1eHLTi+l4//4fMwk" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.js" integrity="sha384-ern5NCRqs6nJ/a4Ik0nB9hnKVH5HwV2XRUYdQl09OB/vvd1Lmmqbg1Mh+mYUclXx" crossorigin="anonymous"></script>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
</head>
<body>
<div id="Main"/>
<script type="text/javascript" src="app.2c9c8d4c1be279b77ba3.js"></script></body>
</html>
```

**Comment by kmader** [comment]
```
<script type="text/javascript" src="app.2c9c8d4c1be279b77ba3.js"></script></body>
```
should be
```
<script type="text/javascript" src=" https://hub.gke.mybinder.org/user/kmader-nbpolynote-uwb2ue4j/polynote/app.2c9c8d4c1be279b77ba3.js"></script></body>
```

**Comment by kmader** [comment]
@betatim do you remember how to get this fixed using https://github.com/jupyterhub/jupyter-server-proxy/?

**Comment by betatim** [comment]
Polynote needs to have a option to configure it to insert a bit of text infront of its links. If it doesn't support that I don't think there is much we can do.

**Comment by kmader** [comment]
Waiting for new release and then will update download URL

**Comment by kmader** [comment]
new slightly different problem: https://github.com/polynote/polynote/issues/655

**Comment by kmader** [comment]
@betatim it works now if you are interested

**Comment by psychemedia** [comment]
So where does this work?

https://mybinder.org/v2/gh/kmader/nbpolynote/master gives me a Binder within which I can launch polynote from the notebook homepage New menu, but whilst Polynote loads the first page, I can't add a new notebook?

**Comment by kmader** [comment]
@psychemedia it is a bit temperamental and sometimes you need to get to polynote and then click refresh in the browser and then you can make a notebook.

**Comment by psychemedia** [comment]
@kmader I tried soft and hard page refreshes at the time, but no joy; I didn't watch the console trace tho' (sorry, my bad); will try to dig a bit more deeply next time. Blitzing through a whole range of things today trying to keep up with where various projects are at!

**Comment by kmader** [comment]
![Screenshot_20191116-174218_Chrome](https://user-images.githubusercontent.com/116120/68996306-7e958200-0898-11ea-90b2-9ca0572c5272.jpg)
It seems to work on my phone at the moment using Chrome

**Comment by psychemedia** [comment]
Nope..still nothing for me on Chrome Version 78.0.3904.97 (Official Build) (64-bit) (Mac)

```
Uncaught TypeError: Cannot read property 'insertBefore' of undefined
    at B4.buildTree (notebook_list.ts:316)
    at B4.addItem (notebook_list.ts:394)
    at ui.ts:128
    at EventTarget.receive (comms.ts:103)

  | buildTree | @ | notebook_list.ts:316
-- | -- | -- | --
  | addItem | @ | notebook_list.ts:394
  | (anonymous) | @ | ui.ts:128
  | receive | @ | comms.ts:103

```

Ah... if I then refresh a couple of times I *do* see the notebook has been listed, and I can click on it and open it...
